default_platform(:ios)

platform :ios do
  desc "Build iOS app"
  lane :build do
    build_app(
      workspace: "ios/App/App.xcworkspace",
      scheme: "App",
      export_method: "app-store",
      output_directory: "./build/ios"
    )
  end
end

platform :android do
  desc "Build Android app"
  lane :build do
    gradle(
      project_dir: "android",
      task: "assembleRelease",
      print_command: false
    )
  end
end
